language: python

python:
  - "2.7"
  - "3.6"

cache: pip

install:
  - pip install flake8 pytest responses

script:
  - flake8 --ignore E501 --filename "*" src/
  - python -B -m pytest -v tests

notifications:
  email: false
